#pragma once

#define HUB_CONNECTION_ATTEMPT_INTERVAL 4000
#define HUB_CONNECTION_EXPIRY_INTERVAL 5000
#define MAX_QUEUED_MESSAGES 16

#define RAW_HID_HUB_COMMAND_ID 0x27
#define QMK_RAW_HID_REPORT_SIZE 32
#define N_UNIQUE_DEVICE_IDS 255
#define DEVICE_ID_UNASSIGNED N_UNIQUE_DEVICE_IDS
#define DEVICE_ID_HUB N_UNIQUE_DEVICE_IDS
#define MAX_REGISTERED_DEVICES 30

enum mouse_passthrough_states {
    MOUSE_PASSTHROUGH_DISCONNECTED = 0,
    MOUSE_PASSTHROUGH_HUB_CONNECTED,
    MOUSE_PASSTHROUGH_REMOTE_CONNECTED,
};

enum report_structure_common {
    REPORT_OFFSET_COMMAND_ID = 0,
    REPORT_OFFSET_DEVICE_ID,
};

enum report_structure_registration {
    REPORT_OFFSET_REGISTRATION = 2,
};

enum report_structure_status {
    REPORT_OFFSET_DEVICE_ID_SELF = 2,
    REPORT_OFFSET_DEVICE_ID_OTHERS
};

enum report_structure_mouse_passthrough {
    REPORT_OFFSET_HANDSHAKE = 2,
    REPORT_OFFSET_DATA_BUTTONS,
    REPORT_OFFSET_DATA_X_MSB,
    REPORT_OFFSET_DATA_X_LSB,
    REPORT_OFFSET_DATA_Y_MSB,
    REPORT_OFFSET_DATA_Y_LSB,
    REPORT_OFFSET_DATA_V_MSB,
    REPORT_OFFSET_DATA_V_LSB,
    REPORT_OFFSET_DATA_H_MSB,
    REPORT_OFFSET_DATA_H_LSB,
    REPORT_OFFSET_CONTROL_BLOCK_BUTTONS,
    REPORT_OFFSET_CONTROL_BLOCK_POINTER,
    REPORT_OFFSET_CONTROL_BLOCK_WHEEL,
    REPORT_OFFSET_CONTROL_SEND_BUTTONS,
    REPORT_OFFSET_CONTROL_SEND_POINTER,
    REPORT_OFFSET_CONTROL_SEND_WHEEL,
    REPORT_OFFSET_RESET,
};
